import { getState, saveState } from "./lib/store.mjs";
import * as cheerio from "cheerio";
import crypto from "node:crypto";

const STATES=["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","District of Columbia","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"];
const SCANNER_VERSION="2.7";
// Direct, food-specific agency surfaces prevent a general state-directory outage or
// bot challenge from erasing an otherwise valid jurisdiction check. Every route is
// an official government page; alternates are tried only when the primary fails.
const DIRECT_SURFACES={
 "Arkansas":["https://healthy.arkansas.gov/article-sitemap.xml","https://healthy.arkansas.gov/programs-services/public-health-safety/food-protection-inspection-portal/"],
 "California":["https://pressreleases.cdfa.ca.gov/","https://www.cdph.ca.gov/Programs/CEH/DFDCS/Pages/FDBPrograms/FoodSafetyProgram/FoodRecalls.aspx"],
 "Delaware":["https://dhss.delaware.gov/dph/homepage/about/sections/hsp/licenses-and-permits/food-protection/food-safety/"],
 "Maine":["https://www.maine.gov/dhhs/mecdc/healthy-living/health-and-safety/food-safety/food-related-illnesses"],
 "Massachusetts":["https://www.mass.gov/orgs/department-of-public-health/news","https://www.mass.gov/info-details/food-safety-recalls-news-alerts","https://www.mass.gov/food-safety","https://www.mass.gov/orgs/department-of-public-health"],
 "Michigan":["https://www.michigan.gov/mdard/food-dairy/food-safety/recalls","https://www.michigan.gov/mdard/food-dairy/food-safety","https://www.michigan.gov/mdard"],
 "Montana":["https://dphhs.mt.gov/publichealth/EHFS/recalls"],
 "Nebraska":["https://nda.nebraska.gov/fscp/foods/recalls"],
 "Nevada":["https://agri.nv.gov/News/","https://www.dpbh.nv.gov/"],
 "New Hampshire":["https://www.dhhs.nh.gov/programs-services/environmental-health-and-you/food-protection","https://www.dhhs.nh.gov/news-events/press-releases"],
 "New Mexico":["https://www.env.nm.gov/foodprogram/"],
 "North Dakota":["https://www.hhs.nd.gov/health/food-and-lodging"],
 "Tennessee":["https://www.tn.gov/agriculture/consumers/food-safety/recalls.html"],
 "Texas":["https://www.dshs.texas.gov/food-manufacturers-wholesalers-warehouses/food-alerts-recalls-affecting-texas"]
};
const FOOD_RE=/\b(?:food|foodborne|outbreak|recall|salmonella|listeria|e\.?\s*coli|stec|cyclospora|botul|sprout|produce|lettuce|fruit|vegetable|dairy|cheese|meat|poultry|egg|seafood|formula|pepper|onion|cucumber|melon|berry|berries|contaminat|illness|advisory)\b/i;
const NEWS_RE=/\b(?:news|press|media|alerts?|advisories|outbreaks?|recalls?|food\s*safety)\b/i;
const HEALTH_RE=/\b(?:department|division|office|bureau).*\b(?:health|public health)\b|\b(?:health|public health).*\b(?:department|division|office|bureau)\b/i;
const clean=v=>String(v||"").replace(/\s+/g," ").trim();
const slug=v=>clean(v).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const idslug=v=>clean(v).toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");
const hash=v=>crypto.createHash("sha256").update(String(v)).digest("hex").slice(0,20);
async function fetchPage(url,ms=9000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{signal:c.signal,redirect:"follow",headers:{accept:"text/html,application/xhtml+xml,*/*;q=0.8","accept-language":"en-US,en;q=0.9","cache-control":"no-cache","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/128.0 Safari/537.36"}})}finally{clearTimeout(t)}}
function governmentish(url){try{const h=new URL(url).hostname.toLowerCase();return h.endsWith(".gov")||h.includes(".gov.")||h.endsWith(".us")||h.endsWith(".state.us")}catch{return false}}
async function resolveHealthAgency(state){
 const directory=`https://www.usa.gov/states/${slug(state)}`;
 const r=await fetchPage(directory,12000);if(!r.ok)throw new Error(`USA.gov state directory ${r.status}`);
 const $=cheerio.load(await r.text()),candidates=[];
 $("a[href]").each((_,a)=>{const text=clean($(a).text()),href=$(a).attr("href")||"";if(!HEALTH_RE.test(text))return;try{const u=new URL(href,directory);if(u.hostname.endsWith("usa.gov")||!governmentish(u.toString()))return;let score=8;if(/department of health|public health/i.test(text))score+=6;if(/health/i.test(text))score+=2;candidates.push({url:u.toString(),text,score})}catch{}});
 candidates.sort((a,b)=>b.score-a.score);if(!candidates.length)throw new Error("authoritative health-agency link not resolved from USA.gov state directory");
 return {directory,url:candidates[0].url,label:candidates[0].text};
}
function findNews(html,base){const $=cheerio.load(html),host=new URL(base).hostname,c=[];$("a[href]").each((_,a)=>{const txt=clean($(a).text()),href=$(a).attr("href")||"";if(!NEWS_RE.test(`${txt} ${href}`))return;try{const u=new URL(href,base);if(!/^https?:$/.test(u.protocol)||!governmentish(u.toString()))return;const score=(u.hostname===host?6:0)+(/outbreak|recall|food/i.test(`${txt} ${href}`)?5:0)+(/news|press|alert/i.test(`${txt} ${href}`)?2:0);c.push({url:u.toString(),score})}catch{}});c.sort((a,b)=>b.score-a.score);return c[0]?.url||null}
function signal(state,title,url,summary,agency){const id=`STATE-${idslug(state).toUpperCase()}-${hash(title+url)}`;return {id,title,product:title,company:"",hazard:"State food-safety signal",severity:/listeria|e\.?\s*coli|stec|botul/i.test(`${title} ${summary}`)?"HIGH":"WATCH",status:"CORROBORATING",category:"State public-health signal",states:[state],distribution:state,source:agency||`${state} public health authority`,sourcePostedAt:null,updatedAt:new Date().toISOString(),verifiedAt:null,summary:clean(summary||title).slice(0,1600),lots:[],evidence:[{type:"AGENCY",status:"DETECTED",source:agency||`${state} public health authority`,text:clean(summary||title).slice(0,1600),url}],entities:[{id:`event-${id}`,type:"Incident",name:title},{id:`geo-${id}`,type:"Geography",name:state}],links:[[ `event-${id}`,`geo-${id}`,"reported in"]],workflowStep:1,rawSource:`state_${idslug(state)}`,earlyWarningSignal:true}}
function titleFromUrl(value){try{const parts=new URL(value).pathname.split("/").filter(Boolean),last=parts.at(-1)||"";return clean(last.replace(/[-_]+/g," ").replace(/\b\w/g,m=>m.toUpperCase()))}catch{return ""}}
function extract(html,base,state,agency){const $=cheerio.load(html,{xmlMode:/<\?xml|<urlset|<sitemapindex/i.test(html)}),rows=[];$("a[href]").each((_,a)=>{const title=clean($(a).text());if(title.length<8||title.length>240||!FOOD_RE.test(title))return;let url;try{url=new URL($(a).attr("href"),base).toString()}catch{return}if(!governmentish(url))return;const context=clean($(a).parent().text())||title;rows.push(signal(state,title,url,context,agency))});$("loc").each((_,node)=>{const raw=clean($(node).text());let url;try{url=new URL(raw,base).toString()}catch{return}if(!governmentish(url))return;const title=titleFromUrl(url);if(title.length<8||title.length>240||!FOOD_RE.test(title))return;rows.push(signal(state,title,url,`Official agency sitemap entry: ${title}`,agency))});return [...new Map(rows.map(x=>[x.id,x])).values()].slice(0,18)}
async function scanOne(state){const started=Date.now();let resolved=null,lastError=null;try{resolved=await resolveHealthAgency(state)}catch(e){lastError=e}const candidates=[...(DIRECT_SURFACES[state]||[]),...(resolved?.url?[resolved.url]:[])];for(const candidate of [...new Set(candidates)]){try{const r=await fetchPage(candidate,11000);if(!r.ok)throw new Error(`official food-safety surface ${r.status}`);const finalUrl=r.url||candidate;if(!governmentish(finalUrl))throw new Error("official surface redirected outside a government domain");const html=await r.text(),agency=resolved?.label||`${state} food-safety authority`;let signals=extract(html,finalUrl,state,agency);const news=findNews(html,finalUrl);if(news&&news!==finalUrl){try{const nr=await fetchPage(news,7000);if(nr.ok&&governmentish(nr.url||news))signals=[...signals,...extract(await nr.text(),nr.url||news,state,agency)]}catch{}}signals=[...new Map(signals.map(x=>[x.id,x])).values()].slice(0,24);return {state,id:`state_${idslug(state)}`,status:"ONLINE",officialUrl:finalUrl,agency,directoryUrl:resolved?.directory||`https://www.usa.gov/states/${slug(state)}`,signals,note:`official state food-safety surface checked; ${signals.length} food-safety links surfaced`,durationMs:Date.now()-started}}catch(e){lastError=e}}return {state,id:`state_${idslug(state)}`,status:"DEGRADED",officialUrl:candidates[0]||resolved?.url||null,agency:resolved?.label||null,directoryUrl:resolved?.directory||`https://www.usa.gov/states/${slug(state)}`,signals:[],note:String(lastError?.message||lastError||"official route unavailable"),durationMs:Date.now()-started}}
function merge(existing,incoming,now){const m=new Map((existing||[]).map(x=>[x.id,x]));for(const raw of incoming){const old=m.get(raw.id);m.set(raw.id,old?{...old,...raw,firstSeenAt:old.firstSeenAt||now,lastObservedAt:now,observationCount:(old.observationCount||1)+1}:{...raw,firstSeenAt:now,lastObservedAt:now,observationCount:1})}return [...m.values()].sort((a,b)=>new Date(b.lastObservedAt||b.updatedAt||0)-new Date(a.lastObservedAt||a.updatedAt||0)).slice(0,1800)}
export async function runStateScan(){const state=await getState(),startedAt=new Date().toISOString();const results=await Promise.all(STATES.map(s=>scanOne(s)));const finishedAt=new Date().toISOString(),incoming=results.flatMap(x=>x.signals||[]),incidents=merge(state.incidents||[],incoming,finishedAt);const nonState=(state.sourceHealth||[]).filter(x=>!String(x.id||"").startsWith("state_"));const stateHealth=results.map(r=>({id:r.id,name:`${r.state} state public-health scan`,family:"State / Local",status:r.status,lastChecked:finishedAt,note:r.note,url:r.officialUrl,directoryUrl:r.directoryUrl,agency:r.agency}));const online=results.filter(x=>x.status==="ONLINE").length,degraded=results.length-online;const coverage={scannerVersion:SCANNER_VERSION,total:51,checked:results.length,online,degraded,signals:incoming.length,lastSync:finishedAt,startedAt,authoritativeResolved:results.filter(x=>x.officialUrl&&x.agency&&x.status==="ONLINE").length,states:results.map(({state,status,note,officialUrl,agency,directoryUrl,durationMs})=>({state,status,note,officialUrl,agency,directoryUrl,durationMs}))};const next={...state,meta:{...(state.meta||{}),stateScanLastSync:finishedAt,stateScanCycleMinutes:30,stateScanVersion:SCANNER_VERSION},incidents,sourceHealth:[...nonState,...stateHealth],stateCoverage:coverage,changes:[{time:finishedAt,title:"51-jurisdiction authoritative state surveillance cycle complete",detail:`51/51 attempted · ${online} online · ${degraded} degraded · ${incoming.length} state signals · ${coverage.authoritativeResolved}/51 authoritative health agencies resolved.`},...(state.changes||[])].slice(0,350)};await saveState(next);return next}
