export const SOURCE_REGISTRY = [
  {id:"fda_openfda",name:"FDA openFDA Food Enforcement",family:"Federal",kind:"api",active:true,authority:true,url:"https://api.fda.gov/food/enforcement.json"},
  {id:"fda_outbreaks",name:"FDA Active Foodborne Outbreak Investigations",family:"Federal",kind:"web",active:true,authority:true,url:"https://www.fda.gov/food/outbreaks-foodborne-illness/investigations-foodborne-illness-outbreaks"},
  {id:"fda_food_events",name:"FDA Food Adverse Events",family:"Federal",kind:"api",active:true,authority:true,url:"https://api.fda.gov/food/event.json",note:"Optional FDA_API_KEY increases rate limits"},
  {id:"usda_fsis",name:"USDA FSIS Recall / Public Health Alerts",family:"Federal",kind:"api+bridge",active:true,authority:true,url:"https://www.fsis.usda.gov/fsis/api/recall/v/1"},

  {id:"fda_import_alerts",name:"FDA Import Alerts",family:"Import / Port",kind:"official-web-data",active:false,authority:true,url:"https://www.fda.gov/industry/import-alerts",note:"Real-time FDA import-control evidence by product, firm, manufacturer, shipper, importer and country of origin. Planned U.S.-relevance correlation source; not a contamination finding by itself."},
  {id:"fda_import_refusals",name:"FDA Import Refusals",family:"Import / Port",kind:"official-web-data",active:false,authority:true,url:"https://www.fda.gov/industry/fda-import-process/import-refusals",note:"FDA refusal/enforcement evidence for detained imported shipments. Planned correlation source; refusal reason must be preserved."},
  {id:"usda_aphis_acir",name:"USDA APHIS Agricultural Commodity Import Requirements",family:"Import / Port",kind:"official-database",active:false,authority:true,url:"https://acir.aphis.usda.gov/",note:"Commodity/country admissibility and plant-health import requirements. Context and provenance evidence only; never treated as proof of food contamination."},

  {id:"usda_ams",name:"USDA AMS MyMarketNews",family:"Agriculture / Movement",kind:"api",active:false,authority:true,url:"https://marsapi.ams.usda.gov/services/v1.2/reports",note:"Authenticated production validation uses USDA_AMS_API_KEY. Shipping-point, specialty-crop and market-movement data provide domestic origin/movement context; not contamination evidence."},
  {id:"usda_nass_quickstats",name:"USDA NASS Quick Stats",family:"Farms / Growing Regions",kind:"api+dataset",active:false,authority:true,url:"https://quickstats.nass.usda.gov/",note:"Farm, crop, livestock, county and state production context, including Florida. API connector planned; agricultural statistics are provenance/risk context, not food-safety findings."},
  {id:"usda_nass_florida",name:"USDA NASS Florida Agriculture",family:"Farms / Growing Regions",kind:"official-dataset",active:false,authority:true,url:"https://www.nass.usda.gov/Statistics_by_State/Florida/",note:"Florida crop, livestock, county and production context produced in cooperation with FDACS. Targeted Florida growing-region layer; not contamination evidence."},

  {id:"cdc_content",name:"CDC Current Multistate Foodborne Investigations",family:"Federal",kind:"official-web-data",active:false,managed:true,authority:true,url:"https://www.cdc.gov/foodborne-outbreaks/outbreaks/index.html",note:"Dedicated 30-minute connector validates CDC's current active-investigation counts; product-level notices appear only when CDC publishes them."},
  {id:"mn_health_food",name:"Minnesota Health + Agriculture Food Signals",family:"State / Local",kind:"web",active:false,managed:true,authority:true,url:"https://www.health.state.mn.us/news",note:"Superseded by 51-jurisdiction authoritative state scan; retained for targeted expansion"},
  {id:"wi_health_food",name:"Wisconsin DHS Outbreaks + Recalls",family:"State / Local",kind:"web",active:false,managed:true,authority:true,url:"https://www.dhs.wisconsin.gov/outbreaks/index.htm",note:"Superseded by 51-jurisdiction authoritative state scan; retained for targeted expansion"},
  {id:"uk_fsa_alerts",name:"UK Food Standards Agency Alerts",family:"International",kind:"api",active:false,authority:true,url:"https://data.food.gov.uk/food-alerts/",note:"Production validation source. Foreign alerts remain international-watch intelligence unless verified/corroborated for U.S. relevance."},
  {id:"trader_joes_recalls",name:"Trader Joe’s Food Safety & Product Recalls",family:"Retailer",kind:"web",active:false,authority:false,url:"https://www.traderjoes.com/home/announcements?category=recalls",note:"Parser retained but disabled in production until a fresh source-specific runtime validation passes"},
  {id:"noaa_enso",name:"NOAA/CPC ENSO + El Niño",family:"Climate",kind:"web",active:true,authority:true,url:"https://www.cpc.ncep.noaa.gov/products/analysis_monitoring/enso_advisory/ensodisc.html",note:"Contextual climate intelligence — never proof of food contamination"},
  {id:"nws_hazards",name:"NWS Flood + Heat + Tropical Hazards",family:"Climate",kind:"api",active:true,authority:true,url:"https://api.weather.gov/alerts/active",note:"No API key required; context only"},
  {id:"cfia_recalls",name:"Canada Food Recalls & Safety Alerts",family:"International",kind:"rss",active:false,authority:true,url:"https://recalls-rappels.canada.ca/en/feed/cfia-alerts-recalls",note:"Production validation source. Canadian alerts require U.S.-relevance evidence before appearing as U.S.-affected incidents."},

  {id:"states",name:"State Health + Agriculture Departments",family:"State / Local",kind:"registry",active:false,display:false,authority:true,note:"Represented publicly by the separate 51-jurisdiction coverage result"},
  {id:"locals",name:"County + City Health Departments",family:"State / Local",kind:"registry",active:false,display:false,authority:true,note:"Expansion registry — not counted as live"},
  {id:"international",name:"International Food Safety Authorities",family:"International",kind:"registry",active:false,display:false,authority:true,note:"Expansion registry — not counted as live"},
  {id:"eu_rasff",name:"EU RASFF Window",family:"International",kind:"web",active:false,display:false,authority:true,url:"https://food.ec.europa.eu/food-safety/rasff_en",note:"Public portal validated; notification normalization not yet counted as live"},
  {id:"ncbi_pathogen_detection",name:"NCBI Pathogen Detection",family:"Laboratory / Genomics",kind:"official-dataset",active:false,display:false,authority:true,url:"https://www.ncbi.nlm.nih.gov/pathogens/",note:"Priority laboratory connector for food, environmental and clinical isolate clusters. Genomic proximity is an investigative signal, not proof that a specific product caused illness."},
  {id:"cdc_nors",name:"CDC National Outbreak Reporting System",family:"Epidemiology",kind:"official-dashboard",active:false,display:false,authority:true,url:"https://wwwn.cdc.gov/norsdashboard",note:"Historical outbreak analytics and trend baseline; not a real-time alert feed."},
  {id:"fsis_establishments",name:"USDA FSIS Meat, Poultry and Egg Product Establishment Directory",family:"Facilities",kind:"official-dataset",active:false,display:false,authority:true,url:"https://www.fsis.usda.gov/inspection/establishments/meat-poultry-and-egg-product-inspection-directory",note:"Priority facility-identity and establishment-number enrichment for FSIS records; not an incident feed."},
  {id:"nyc_food_inspections",name:"NYC DOHMH Restaurant Inspection Results",family:"Municipal Operations",kind:"open-data-api",active:false,display:false,authority:true,url:"https://data.cityofnewyork.us/resource/43nn-pn8j.json",note:"Candidate municipal pilot for facility compliance and suspected foodborne-illness inspection context; must remain separate from product recalls."},
  {id:"chicago_food_inspections",name:"Chicago Food Inspections",family:"Municipal Operations",kind:"open-data-api",active:false,display:false,authority:true,url:"https://data.cityofchicago.org/resource/4ijn-s7e5.json",note:"Candidate municipal pilot for failed inspections and suspected food-poisoning inspections; must remain separate from product recalls."},
  {id:"sf_food_inspections",name:"San Francisco Health Inspection Scores",family:"Municipal Operations",kind:"open-data-api",active:false,display:false,authority:true,url:"https://data.sfgov.org/Health-and-Social-Services/Health-Inspection-Scores-2024-Present-/tvy3-wexg",note:"Candidate municipal facility-risk layer; not evidence of a national product recall."},
  {id:"fsanz_recalls",name:"Food Standards Australia New Zealand Recalls",family:"International",kind:"official-web-data",active:false,display:false,authority:true,url:"https://www.foodstandards.gov.au/food-recalls",note:"Candidate international recall connector; alerts remain foreign-watch signals until U.S. relevance is verified."},
  {id:"nz_mpi_recalls",name:"New Zealand Ministry for Primary Industries Food Recalls",family:"International",kind:"official-web-data",active:false,display:false,authority:true,url:"https://www.mpi.govt.nz/food-safety-home/food-recalls-and-complaints/recalled-food-products/",note:"Candidate international recall connector; U.S. relevance must be verified."},
  {id:"infosan",name:"FAO/WHO INFOSAN",family:"International Coordination",kind:"partnership",active:false,display:false,authority:true,url:"https://www.who.int/groups/fao-who-international-food-safety-authorities-network-infosan",note:"High-value international coordination source, but incident-level access may require official participation rather than public scraping."},
  {id:"retailers",name:"Retailers + Manufacturers",family:"Industry",kind:"registry",active:false,display:false,authority:false,note:"Expansion registry — not counted as live"},
  {id:"suppliers",name:"Suppliers + Distributors",family:"Industry",kind:"registry",active:false,display:false,authority:false,note:"Expansion registry — not counted as live"},
  {id:"labs_science",name:"Laboratories + Scientific Literature",family:"Science",kind:"registry",active:false,display:false,authority:false,note:"Expansion registry — not counted as live"},
  {id:"water_irrigation",name:"Water + Irrigation + Environmental Quality",family:"Environment",kind:"registry",active:false,display:false,authority:false,note:"Expansion registry — never used as contamination proof without official incident evidence"},
  {id:"ag_environment",name:"Agriculture + Growing Region Conditions",family:"Environment",kind:"registry",active:false,display:false,authority:false,note:"Expansion registry — farm/growing-region risk context only"},
  {id:"logistics",name:"Ports + Logistics + Cold Chain",family:"Logistics",kind:"registry",active:false,display:false,authority:false,note:"Expansion registry for port-of-entry, movement and cold-chain context; shipment-level claims require authoritative evidence"},
  {id:"emerging",name:"News + Consumer + Emerging Signals",family:"Emerging",kind:"registry",active:false,display:false,authority:false,note:"Expansion registry — never treated as verified without corroboration"}
];

export const FOOD_CATEGORIES = ["Produce","Meat","Poultry","Eggs","Seafood","Dairy","Frozen foods","Prepared foods","Bakery","Snacks","Beverages","Infant foods/formula","Pet/animal food","Imported foods","Ingredients","Spices","Sauces","Grains","Nuts","Confectionery","Food service","Institutional foods","Other food-safety relevant"];
export const INTELLIGENCE_STATES = ["DETECTED","CORROBORATING","VERIFIED","CONTRADICTED","RETRACTED","RESOLVED"];
